deployments:
- build_id: 1920cde3-4170-4a13-8326-4769afba80b2
  deployed_at: '2024-10-23T11:00:35.560041'
  deployment_id: 41d4614a-e0f4-435a-96af-e21ed546cdc7
  deployment_run: bc247fc5-1a64-4da0-8126-133b1f683763
  flavour: vanilla
  image: jhnnsrs/renderer:0.0.2-vanilla
  inspection:
    requirements:
      datalayer:
        description: An instance of ArkitektNext Datalayer to make requests to the
          user's data
        optional: true
        service: live.arkitekt.s3
      fluss:
        description: An instance of ArkitektNext fluss to retrieve graphs from
        optional: false
        service: live.arkitekt.fluss
      kabinet:
        description: An instance of ArkitektNext Kabinet to retrieve nodes from
        optional: false
        service: live.arkitekt.kabinet
      livekit:
        description: An instance of ArkitektNext Lok to authenticate the user
        optional: false
        service: io.livekit.livekit
      lok:
        description: An instance of ArkitektNext Lok to authenticate the user
        optional: false
        service: live.arkitekt.lok
      mikro:
        description: An instance of ArkitektNext Mikro to make requests to the user's
          data
        optional: true
        service: live.arkitekt.mikro
      rekuest:
        description: An instance of ArkitektNext Rekuest to assign to nodes
        optional: false
        service: live.arkitekt.rekuest
      unlok:
        description: An instance of ArkitektNext Lok to authenticate the user
        optional: false
        service: live.arkitekt.lok
    size: 659465051
    templates:
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
              \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \  }\n}"
            ward: mikro
          description: The image
          identifier: '@mikro/image'
          key: image
          kind: STRUCTURE
          label: image
          nullable: false
          scope: GLOBAL
        collections: []
        description: This function renders the image
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: Render
        portGroups: []
        returns:
        - assignWidget:
            kind: SEARCH
            query: "query SearchSnapshots($search: String, $values: [ID!]) {\n  options:\
              \ snapshots(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \  }\n}"
            ward: mikro
          description: The thumbnail
          identifier: '@mikro/snapshot'
          key: return0
          kind: STRUCTURE
          nullable: false
          scope: GLOBAL
        stateful: false
      dependencies: []
      dynamic: false
      interface: render
  manifest:
    author: jhnnsrs
    created_at: '2024-10-23T11:00:31.324535'
    entrypoint: app
    identifier: renderer
    scopes:
    - read
    version: 0.0.2
  selectors: []
latest_deployment_run: 623bacc7-a562-4900-833b-51305d623caf
